<a href="https://colab.research.google.com/github/iamanolive/seven-days-of-AI/blob/main/tensorflow-tutorials/introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import tensorflow as tf

# creating tensors

In [9]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

# ranks or degrees of tensors

In [27]:
rank1_tensor = tf.Variable(["Test", "Ok", "Somebody", "Somebody"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"], ["ok", "ok"]], tf.string)

In [28]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [29]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [30]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

# shapes of tensors

In [31]:
rank1_tensor.shape

TensorShape([4])

In [32]:
rank2_tensor.shape

TensorShape([3, 2])

# changing shapes

In [37]:
tensor1 = tf.ones([1, 2, 3])
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1])

In [38]:
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [39]:
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [44]:
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
