<a href="https://colab.research.google.com/github/iamanolive/seven-days-of-AI/blob/main/python-libraries/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

# basic numpy arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([0, 0.5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:-1]

array([2, 3])

In [13]:
a[::3]

array([1, 4])

In [14]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [15]:
b[[0, 2, -1]]

array([0., 1., 2.])

# array types

In [18]:
a

array([1, 2, 3, 4])

In [19]:
a.dtype

dtype('int64')

In [20]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [21]:
b.dtype

dtype('float64')

In [27]:
np.array([1, 2, 3, 4], dtype = np.float64)

array([1., 2., 3., 4.])

In [28]:
np.array([1, 2, 3, 4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [29]:
c = np.array(["a", "b", "c"])

In [30]:
c.dtype

dtype('<U1')

In [31]:
# creating an object
d = np.array([{"a" : 1}, sys])

In [32]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [34]:
d.dtype

dtype('O')

# dimensions and shapes

In [35]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [36]:
A.shape # rows by columns

(2, 3)

In [37]:
A.ndim

2

In [38]:
A.size

6

In [41]:
B = np.array([
    [
        [1, 2, 3],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [42]:
B.shape

(2, 2, 3)

In [43]:
B.ndim

3

In [44]:
B.size

12

# indexing and slicing of matrices

In [64]:
# square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [65]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
A[1]

array([4, 5, 6])

In [67]:
A[1][0]

4

In [68]:
A[1, 0]

4

In [69]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [71]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [72]:
A[:2, 2:]

array([[3],
       [6]])

In [73]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
A[1] = np.array([10, 10, 10])

In [75]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [76]:
A[2] = 99

In [78]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# summary statistics

In [81]:
a = np.array([1, 2, 3, 4])

In [82]:
a.sum()

10

In [83]:
a.mean()

2.5

In [84]:
a.std() # standard deviation

1.118033988749895

In [85]:
a.var() # dispersion / spread in data

1.25

In [86]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [87]:
A.sum()

45

In [88]:
A.mean()

5.0

In [89]:
A.std()

2.581988897471611

In [91]:
A.sum(axis = 0)

array([12, 15, 18])

In [92]:
A.sum(axis = 1)

array([ 6, 15, 24])

In [93]:
A.mean(axis = 0)

array([4., 5., 6.])

In [94]:
A.mean(axis = 1)

array([2., 5., 8.])

In [95]:
A.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [96]:
# increase number of axis if more dimensions
A.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

# broadcasting and vectorized operations

In [98]:
a = np.arange(4)

In [113]:
a # numpy is an immutable-first library

array([200, 201, 202, 203])

In [107]:
a + 10

array([110, 111, 112, 113])

In [108]:
a

array([100, 101, 102, 103])

In [109]:
a * 10

array([1000, 1010, 1020, 1030])

In [110]:
a += 100

In [111]:
a

array([200, 201, 202, 203])

In [112]:
l = [0, 1, 2, 3]

In [117]:
[i * 10 for i in l] # not optimized

[0, 10, 20, 30]

In [118]:
a = np.arange(4)

In [119]:
a

array([0, 1, 2, 3])

In [122]:
b = np.array([10, 10, 10, 10])

In [123]:
a + b

array([10, 11, 12, 13])

In [124]:
a * b

array([ 0, 10, 20, 30])

# boolean arrays (masks)

In [125]:
a = np.arange(4)

In [128]:
a

array([0, 1, 2, 3])

In [129]:
a[0], a[-1]

(0, 3)

In [130]:
a[[0, -1]] # multi-index selection

array([0, 3])

In [134]:
a[[True, False, False, True]] # boolean selection

array([0, 3])

In [135]:
a >= 2

array([False, False,  True,  True])

In [136]:
a[a >= 2]

array([2, 3])

In [139]:
a.mean()

1.5

In [140]:
a[a > a.mean()]

array([2, 3])

In [143]:
a[~(a > a.mean())]

array([0, 1])

In [147]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [148]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [155]:
A = np.random.randint(100, size = (3, 3))

In [156]:
A

array([[22, 67, 68],
       [53, 34, 15],
       [ 9, 95,  0]])

In [159]:
C = A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [160]:
A

array([[22, 67, 68],
       [53, 34, 15],
       [ 9, 95,  0]])

In [161]:
C

array([22, 68, 34,  9,  0])

In [162]:
A > 30

array([[False,  True,  True],
       [ True,  True, False],
       [False,  True, False]])

In [163]:
A[A > 30]

array([67, 68, 53, 34, 95])

# linear algebra

In [164]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [165]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [166]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [167]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [168]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [169]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# size of objects in memory

In [171]:
sys.getsizeof(1)

28

In [172]:
sys.getsizeof(0)

24

In [173]:
sys.getsizeof(10 ** 100)

72

In [174]:
# the size of numpy ints is much smaller
np.dtype(int).itemsize

8

In [185]:
np.dtype(np.int8).itemsize

1

In [175]:
np.dtype(float).itemsize

8

In [176]:
sys.getsizeof([1])

64

In [177]:
np.array([1]).nbytes

8

In [178]:
l = list(range(1000))

In [180]:
a = np.arange(1000)

In [181]:
# numpy has faster performance
%time np.sum(a ** 2)

CPU times: user 132 µs, sys: 14 µs, total: 146 µs
Wall time: 151 µs


332833500

In [183]:
%time sum([x ** 2 for x in l])

CPU times: user 303 µs, sys: 33 µs, total: 336 µs
Wall time: 339 µs


332833500

# useful numpy functions

### `random`

In [186]:
np.random.random(size = 2)

array([0.69106505, 0.67247227])

In [187]:
np.random.normal(size = 2)

array([-0.23184412,  0.97849095])

In [188]:
np.random.rand(2, 4)

array([[0.92247992, 0.3163662 , 0.88138992, 0.44366715],
       [0.11220146, 0.71502993, 0.40677366, 0.30540461]])

### `arange`

In [189]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [191]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### `reshape`

In [192]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [193]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### `linspace`

In [200]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [201]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [202]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### `zeros`, `ones`, `empty`

In [203]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [204]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [207]:
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [208]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [209]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [215]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [216]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### `identity` and `eye`

In [217]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [219]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [220]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [221]:
np.eye(8, 4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [222]:
np.eye(8, 4, k = 3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [223]:
"hello world"[6]

'w'